language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sirgarfield/docker-react .
script:
  -  docker run -e CI=true sirgarfield/docker-react npm run test